# Generated by Django 4.2.5 on 2023-10-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techlabo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tech_stack",
            field=models.ManyToManyField(
                blank=True, null=True, to="techlabo.techstack"
            ),
        ),
    ]
