# Generated by Django 4.2.5 on 2023-10-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "techlabo",
            "0002_alter_userprofile_github_alter_userprofile_linkedin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="About Me"),
        ),
    ]
